import Head from "next/head";
import Header from "../components/header/header";
import Hero from "../components/sections/hero/hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sakil Ahmed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <Header />
        <Hero />
      </main>
    </>
  );
}
